/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  socialImage?: EditorialImage
  noIndex?: boolean
}

export type ContactTeaser = {
  _type: 'contactTeaser'
  heading: string
  text: string
  linkLabel: string
}

export type Callout = {
  _type: 'callout'
  tone: 'note' | 'important'
  title?: string
  body: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Gallery = {
  _type: 'gallery'
  images: Array<
    {
      _key: string
    } & EditorialImage
  >
}

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & EditorialImage)
  | ({
      _key: string
    } & Gallery)
  | ({
      _key: string
    } & Callout)
>

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type EditorialImage = {
  _type: 'editorialImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  caption?: string
}

export type LegalPage = {
  _id: string
  _type: 'legalPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  body: PortableText
  updatedAt?: string
  seo?: Seo
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description: string
  publishedAt: string
  updatedAt?: string
  featured?: boolean
  coverImage?: EditorialImage
  topics?: Array<string>
  body: PortableText
  related?: Array<
    {
      _key: string
    } & PostReference
  >
  seo?: Seo
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  summary: string
  publishedAt: string
  featured?: boolean
  coverImage: EditorialImage
  role?: string
  disciplines?: Array<string>
  projectUrl?: string
  body: PortableText
  gallery?: Gallery
  seo?: Seo
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  introduction: string
  body?: PortableText
  seo?: Seo
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  introduction: string
  portrait?: EditorialImage
  body: PortableText
  contactTeaser?: ContactTeaser
  seo?: Seo
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero: {
    eyebrow?: string
    heading: string
    lead: string
    projectsLinkLabel: string
    contactLinkLabel: string
  }
  introduction?: PortableText
  portrait?: EditorialImage
  projectsHeading: string
  projectsOverviewLinkLabel: string
  featuredProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  postsHeading: string
  postsOverviewLinkLabel: string
  contactTeaser?: ContactTeaser
  seo?: Seo
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteTitle: string
  siteDescription: string
  ownerName: string
  ownerRole?: string
  email?: string
  socialLinks?: Array<{
    label: string
    url: string
    _key: string
  }>
  defaultSocialImage?: EditorialImage
  projectsSeo?: Seo
  blogSeo?: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Seo
  | ContactTeaser
  | Callout
  | Gallery
  | PortableText
  | SanityImageAssetReference
  | EditorialImage
  | LegalPage
  | PostReference
  | Post
  | Slug
  | Project
  | ContactPage
  | AboutPage
  | ProjectReference
  | HomePage
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/sanity/queries/index.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    _id,    siteTitle,    siteDescription,    ownerName,    ownerRole,    email,    socialLinks[]{_key, label, url},    defaultSocialImage{      ...,      asset->{_id, url, metadata{dimensions, lqip}}    },    projectsSeo{      ...,      socialImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    },    blogSeo{      ...,      socialImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: 'siteSettings'
  siteTitle: string
  siteDescription: string
  ownerName: string
  ownerRole: string | null
  email: string | null
  socialLinks: Array<{
    _key: string
    label: string
    url: string
  }> | null
  defaultSocialImage: {
    _type: 'editorialImage'
    asset: {
      _id: string
      url: string
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
  } | null
  projectsSeo: {
    _type: 'seo'
    title?: string
    description?: string
    socialImage: {
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    } | null
    noIndex?: boolean
  } | null
  blogSeo: {
    _type: 'seo'
    title?: string
    description?: string
    socialImage: {
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    } | null
    noIndex?: boolean
  } | null
} | null

// Source: src/sanity/queries/index.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{    _id,    hero,    introduction,    portrait{      ...,      asset->{_id, url, metadata{dimensions, lqip}}    },    projectsHeading,    projectsOverviewLinkLabel,    featuredProjects[]->{      _id,      title,      "slug": slug.current,      summary,      publishedAt,      role,      disciplines,      coverImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    },    postsHeading,    postsOverviewLinkLabel,    contactTeaser,    seo{      ...,      socialImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    }  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: 'homePage'
  hero: {
    eyebrow?: string
    heading: string
    lead: string
    projectsLinkLabel: string
    contactLinkLabel: string
  }
  introduction: PortableText | null
  portrait: {
    _type: 'editorialImage'
    asset: {
      _id: string
      url: string
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
  } | null
  projectsHeading: string
  projectsOverviewLinkLabel: string
  featuredProjects: Array<{
    _id: string
    title: string
    slug: string
    summary: string
    publishedAt: string
    role: string | null
    disciplines: Array<string> | null
    coverImage: {
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    }
  }> | null
  postsHeading: string
  postsOverviewLinkLabel: string
  contactTeaser: ContactTeaser | null
  seo: {
    _type: 'seo'
    title?: string
    description?: string
    socialImage: {
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    } | null
    noIndex?: boolean
  } | null
} | null

// Source: src/sanity/queries/index.ts
// Variable: HOME_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]    | order(featured desc, publishedAt desc)[0...3]{      _id,      title,      "slug": slug.current,      description,      publishedAt,      updatedAt,      topics,      coverImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    }
export type HOME_POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  description: string
  publishedAt: string
  updatedAt: string | null
  topics: Array<string> | null
  coverImage: {
    _type: 'editorialImage'
    asset: {
      _id: string
      url: string
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
  } | null
}>

// Source: src/sanity/queries/index.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{    _id,    title,    introduction,    portrait{      ...,      asset->{_id, url, metadata{dimensions, lqip}}    },    body,    contactTeaser,    seo{      ...,      socialImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  _id: 'aboutPage'
  title: string
  introduction: string
  portrait: {
    _type: 'editorialImage'
    asset: {
      _id: string
      url: string
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
  } | null
  body: PortableText
  contactTeaser: ContactTeaser | null
  seo: {
    _type: 'seo'
    title?: string
    description?: string
    socialImage: {
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    } | null
    noIndex?: boolean
  } | null
} | null

// Source: src/sanity/queries/index.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage" && _id == "contactPage"][0]{    _id,    title,    introduction,    body,    seo{      ...,      socialImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    }  }
export type CONTACT_PAGE_QUERY_RESULT = {
  _id: 'contactPage'
  title: string
  introduction: string
  body: PortableText | null
  seo: {
    _type: 'seo'
    title?: string
    description?: string
    socialImage: {
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    } | null
    noIndex?: boolean
  } | null
} | null

// Source: src/sanity/queries/index.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(publishedAt desc){    _id,    title,    "slug": slug.current,    summary,    publishedAt,    featured,    role,    disciplines,    coverImage{      ...,      asset->{_id, url, metadata{dimensions, lqip}}    }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  summary: string
  publishedAt: string
  featured: boolean | null
  role: string | null
  disciplines: Array<string> | null
  coverImage: {
    _type: 'editorialImage'
    asset: {
      _id: string
      url: string
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
  }
}>

// Source: src/sanity/queries/index.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    summary,    publishedAt,    role,    disciplines,    projectUrl,    coverImage{      ...,      asset->{_id, url, metadata{dimensions, lqip}}    },    body,    gallery{      images[]{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    },    seo{      ...,      socialImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    }  }
export type PROJECT_QUERY_RESULT = {
  _id: string
  title: string
  slug: string
  summary: string
  publishedAt: string
  role: string | null
  disciplines: Array<string> | null
  projectUrl: string | null
  coverImage: {
    _type: 'editorialImage'
    asset: {
      _id: string
      url: string
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
  }
  body: PortableText
  gallery: {
    images: Array<{
      _key: string
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    }>
  } | null
  seo: {
    _type: 'seo'
    title?: string
    description?: string
    socialImage: {
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    } | null
    noIndex?: boolean
  } | null
} | null

// Source: src/sanity/queries/index.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){    _id,    title,    "slug": slug.current,    description,    publishedAt,    updatedAt,    featured,    topics,    coverImage{      ...,      asset->{_id, url, metadata{dimensions, lqip}}    }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: string
  description: string
  publishedAt: string
  updatedAt: string | null
  featured: boolean | null
  topics: Array<string> | null
  coverImage: {
    _type: 'editorialImage'
    asset: {
      _id: string
      url: string
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
  } | null
}>

// Source: src/sanity/queries/index.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    description,    publishedAt,    updatedAt,    topics,    coverImage{      ...,      asset->{_id, url, metadata{dimensions, lqip}}    },    body,    related[]->{      _id,      title,      "slug": slug.current,      description,      publishedAt    },    "previous": *[      _type == "post" && defined(slug.current) && publishedAt < ^.publishedAt    ] | order(publishedAt desc)[0]{      _id,      title,      "slug": slug.current    },    "next": *[      _type == "post" && defined(slug.current) && publishedAt > ^.publishedAt    ] | order(publishedAt asc)[0]{      _id,      title,      "slug": slug.current    },    seo{      ...,      socialImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    }  }
export type POST_QUERY_RESULT = {
  _id: string
  title: string
  slug: string
  description: string
  publishedAt: string
  updatedAt: string | null
  topics: Array<string> | null
  coverImage: {
    _type: 'editorialImage'
    asset: {
      _id: string
      url: string
      metadata: {
        dimensions: SanityImageDimensions | null
        lqip: string | null
      } | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
  } | null
  body: PortableText
  related: Array<{
    _id: string
    title: string
    slug: string
    description: string
    publishedAt: string
  }> | null
  previous: {
    _id: string
    title: string
    slug: string
  } | null
  next: {
    _id: string
    title: string
    slug: string
  } | null
  seo: {
    _type: 'seo'
    title?: string
    description?: string
    socialImage: {
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    } | null
    noIndex?: boolean
  } | null
} | null

// Source: src/sanity/queries/index.ts
// Variable: LEGAL_PAGE_QUERY
// Query: *[_type == "legalPage" && _id == $id][0]{    _id,    title,    body,    updatedAt,    seo{      ...,      socialImage{        ...,        asset->{_id, url, metadata{dimensions, lqip}}      }    }  }
export type LEGAL_PAGE_QUERY_RESULT = {
  _id: string
  title: string
  body: PortableText
  updatedAt: string | null
  seo: {
    _type: 'seo'
    title?: string
    description?: string
    socialImage: {
      _type: 'editorialImage'
      asset: {
        _id: string
        url: string
        metadata: {
          dimensions: SanityImageDimensions | null
          lqip: string | null
        } | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
    } | null
    noIndex?: boolean
  } | null
} | null

// Source: src/sanity/queries/index.ts
// Variable: SITEMAP_QUERY
// Query: {  "projects": *[_type == "project" && defined(slug.current)]{    "slug": slug.current,    _updatedAt  },  "posts": *[_type == "post" && defined(slug.current)]{    "slug": slug.current,    _updatedAt  }}
export type SITEMAP_QUERY_RESULT = {
  projects: Array<{
    slug: string
    _updatedAt: string
  }>
  posts: Array<{
    slug: string
    _updatedAt: string
  }>
}

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    _id,\n    siteTitle,\n    siteDescription,\n    ownerName,\n    ownerRole,\n    email,\n    socialLinks[]{_key, label, url},\n    defaultSocialImage{\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    },\n    projectsSeo{\n      ...,\n      socialImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    },\n    blogSeo{\n      ...,\n      socialImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT
    '\n  *[_type == "homePage" && _id == "homePage"][0]{\n    _id,\n    hero,\n    introduction,\n    portrait{\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    },\n    projectsHeading,\n    projectsOverviewLinkLabel,\n    featuredProjects[]->{\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      publishedAt,\n      role,\n      disciplines,\n      coverImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    },\n    postsHeading,\n    postsOverviewLinkLabel,\n    contactTeaser,\n    seo{\n      ...,\n      socialImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    }\n  }\n': HOME_PAGE_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current)]\n    | order(featured desc, publishedAt desc)[0...3]{\n      _id,\n      title,\n      "slug": slug.current,\n      description,\n      publishedAt,\n      updatedAt,\n      topics,\n      coverImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    }\n': HOME_POSTS_QUERY_RESULT
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0]{\n    _id,\n    title,\n    introduction,\n    portrait{\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    },\n    body,\n    contactTeaser,\n    seo{\n      ...,\n      socialImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    }\n  }\n': ABOUT_PAGE_QUERY_RESULT
    '\n  *[_type == "contactPage" && _id == "contactPage"][0]{\n    _id,\n    title,\n    introduction,\n    body,\n    seo{\n      ...,\n      socialImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    }\n  }\n': CONTACT_PAGE_QUERY_RESULT
    '\n  *[_type == "project" && defined(slug.current)] | order(publishedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedAt,\n    featured,\n    role,\n    disciplines,\n    coverImage{\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    }\n  }\n': PROJECTS_QUERY_RESULT
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedAt,\n    role,\n    disciplines,\n    projectUrl,\n    coverImage{\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    },\n    body,\n    gallery{\n      images[]{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    },\n    seo{\n      ...,\n      socialImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    }\n  }\n': PROJECT_QUERY_RESULT
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    publishedAt,\n    updatedAt,\n    featured,\n    topics,\n    coverImage{\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    }\n  }\n': POSTS_QUERY_RESULT
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    publishedAt,\n    updatedAt,\n    topics,\n    coverImage{\n      ...,\n      asset->{_id, url, metadata{dimensions, lqip}}\n    },\n    body,\n    related[]->{\n      _id,\n      title,\n      "slug": slug.current,\n      description,\n      publishedAt\n    },\n    "previous": *[\n      _type == "post" && defined(slug.current) && publishedAt < ^.publishedAt\n    ] | order(publishedAt desc)[0]{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    "next": *[\n      _type == "post" && defined(slug.current) && publishedAt > ^.publishedAt\n    ] | order(publishedAt asc)[0]{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    seo{\n      ...,\n      socialImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    }\n  }\n': POST_QUERY_RESULT
    '\n  *[_type == "legalPage" && _id == $id][0]{\n    _id,\n    title,\n    body,\n    updatedAt,\n    seo{\n      ...,\n      socialImage{\n        ...,\n        asset->{_id, url, metadata{dimensions, lqip}}\n      }\n    }\n  }\n': LEGAL_PAGE_QUERY_RESULT
    '{\n  "projects": *[_type == "project" && defined(slug.current)]{\n    "slug": slug.current,\n    _updatedAt\n  },\n  "posts": *[_type == "post" && defined(slug.current)]{\n    "slug": slug.current,\n    _updatedAt\n  }\n}': SITEMAP_QUERY_RESULT
  }
}
